USE YemekSiparisDB;
GO

-- TABLOLAR (BUGÜN SADECE TEMEL KISIM)
CREATE TABLE Musteriler (
    MusteriID INT PRIMARY KEY IDENTITY,
    Ad NVARCHAR(50) NOT NULL,
    Soyad NVARCHAR(50) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Telefon NVARCHAR(15) UNIQUE NOT NULL,
    IsActive BIT DEFAULT 1
);

CREATE TABLE Restoranlar (
    RestoranID INT PRIMARY KEY IDENTITY,
    RestoranAdi NVARCHAR(100) NOT NULL,
    Puan DECIMAL(2,1) CHECK (Puan BETWEEN 1 AND 5),
    ToplamCiro DECIMAL(10,2) DEFAULT 0,
    IsActive BIT DEFAULT 1
);